package nl.mpi.arbil;

import nl.mpi.arbil.util.ApplicationVersion;
        
public class ArbilVersion extends ApplicationVersion {

    /**
     * GENERATED BY ANT - DO NOT EDIT. See the arbil.xml build script.
     */
    public ArbilVersion() {
    	applicationTitle = "Arbil (testing)";
    	applicationIconName = "/nl/mpi/arbil/resources/icons/arbil-testing128x128.png";
    	currentMajor = "2";
    	currentMinor = "4";
    	currentRevision = "33659";
	lastCommitDate = "Last Changed Date: 2012-10-10 15:22:36 +0200 (Wed, 10 Oct 2012)";
	compileDate = "Thu Oct 11 10:39:35 CEST 2012";
	fullInfo = "\nPath: src/main/java/nl/mpi/arbil\nURL: https://svn.mpi.nl/LAT/Arbil/branches/arbil.2.4.x/arbil/src/main/java/nl/mpi/arbil\nRepository Root: https://svn.mpi.nl/LAT\nRepository UUID: d4234c5b-7c33-0410-a85d-91bdcf7faf44\nRevision: 33683\nNode Kind: directory\nSchedule: normal\nLast Changed Author: petwit\nLast Changed Rev: 33659\nLast Changed Date: 2012-10-10 15:22:36 +0200 (Wed, 10 Oct 2012)\n";
    	currentVersionFile = "http://www.mpi.nl/tg/j2se/jnlp/arbil/arbil-testing-current.txt";
    }
}
        