package mpi.metadata.tools.mdeditor.app.gui;

import java.util.Vector;


/**
 * This class hold information generated by a LookAheadContext. This
 * information includes the inportstring, the context, the contextset and a
 * selection interval.
 *
 * @author Don Willems
 * @version 1.0
 */
public class Context {
    private Vector set = new Vector();
    private String context = "";
    private String contextAt = "";
    private SelectionInterval selection;
    private String input = "";

    /**
     * Generates a context from the provided information.
     *
     * @param input The input dtring for which this context was generated.
     * @param context The context for the provided input.
     * @param selection The selection interval that should be selected.
     */
    public Context(String input, String context, SelectionInterval selection) {
        this.input = input;
        this.context = context;
        this.contextAt = context;
        this.selection = selection;
        set.addElement(context);
    }

    /**
     * Generates a context from the provided information.
     *
     * @param input The input dtring for which this context was generated.
     * @param context The context for the provided input.
     * @param contextset The complete set of context.
     * @param selection The selection interval that should be selected.
     */
    public Context(String input, String context, Vector contextset,
        SelectionInterval selection) {
        this.input = input;
        this.context = context;
        this.contextAt = context;
        this.set = contextset;
        this.selection = selection;
    }

    /**
     * Generates a context from the provided information.
     *
     * @param input The input dtring for which this context was generated.
     * @param context The context for the provided input.
     * @param contextAtPos The context for the provided input at the start of
     *        the selection interval.
     * @param contextset The complete set of context.
     * @param selection The selection interval that should be selected.
     */
    public Context(String input, String context, String contextAtPos,
        Vector contextset, SelectionInterval selection) {
        this.input = input;
        this.context = context;
        this.contextAt = contextAtPos;
        this.set = contextset;
        this.selection = selection;
    }

    /**
     * Returns the input for this context.
     *
     * @return The input;
     */
    public String getInput() {
        return input;
    }

    /**
     * Returns the context for the provided input.
     *
     * @return The context.
     */
    public String getContext() {
        return context;
    }

    /**
     * Returns the context for the provided input at the selected position.
     *
     * @return The context.
     */
    public String getContextAtPosition() {
        return contextAt;
    }

    /**
     * Returns the contextset for the provided input.
     *
     * @return The context set.
     */
    public Vector getContextSet() {
        return set;
    }

    /**
     * Returns the selection interval that should be selected in a textfield.
     *
     * @return The selection interval.
     */
    public SelectionInterval getSelectionInterval() {
        return selection;
    }
}
