package nl.mpi.arbil;

import nl.mpi.arbil.util.ApplicationVersion;
        
public class ArbilVersion extends ApplicationVersion {

    /**
     * GENERATED BY ANT - DO NOT EDIT. See the arbil.xml build script.
     */
    public ArbilVersion() {
    	applicationTitle = "Arbil (testing)";
    	applicationIconName = "/nl/mpi/arbil/resources/icons/arbil-testing128x128.png";
    	currentMajor = "2";
    	currentMinor = "4";
    	currentRevision = "31001";
	lastCommitDate = "Last Changed Date: 2012-05-24 16:59:06 +0200 (Thu, 24 May 2012)";
	compileDate = "Fri May 25 15:21:06 CEST 2012";
	fullInfo = "\nPath: src/main/java/nl/mpi/arbil\nURL: https://svn.mpi.nl/LAT/Arbil/branches/arbil.2.4.x/src/main/java/nl/mpi/arbil\nRepository Root: https://svn.mpi.nl/LAT\nRepository UUID: d4234c5b-7c33-0410-a85d-91bdcf7faf44\nRevision: 31000\nNode Kind: directory\nSchedule: normal\nLast Changed Author: twagoo\nLast Changed Rev: 30999\nLast Changed Date: 2012-05-24 16:59:06 +0200 (Thu, 24 May 2012)\n";
    	currentVersionFile = "http://www.mpi.nl/tg/j2se/jnlp/arbil/arbil-testing-current.txt";
    }
}
        