package nl.mpi.arbil.templates;

import java.io.File;
import javax.swing.JCheckBox;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import nl.mpi.arbil.GuiHelper;
import nl.mpi.arbil.LinorgWindowManager;
import nl.mpi.arbil.clarin.CmdiProfileReader;

/*
 * TemplateDialogue.java
 * Created on May 20, 2010, 9:03:29 AM
 * @author Peter.Withers@mpi.nl
 */
public class TemplateDialogue extends javax.swing.JPanel {

    /** Creates new form TemplateDialogue */
    public TemplateDialogue() {
        initComponents();
        populateLists();
        jProgressBar1.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        templatesPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        clarinPanel = new javax.swing.JPanel();

        setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Internal Templates"));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jButton3.setText("New Template");
        jButton3.setToolTipText("Create a new editable template");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3);

        jPanel2.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        org.jdesktop.layout.GroupLayout templatesPanelLayout = new org.jdesktop.layout.GroupLayout(templatesPanel);
        templatesPanel.setLayout(templatesPanelLayout);
        templatesPanelLayout.setHorizontalGroup(
            templatesPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 342, Short.MAX_VALUE)
        );
        templatesPanelLayout.setVerticalGroup(
            templatesPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 288, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(templatesPanel);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Clarin Profiles"));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jButton1.setText("Reload Clarin Profiles");
        jButton1.setToolTipText("Download the latest clarin profiles");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jPanel4.add(jProgressBar1);

        jPanel3.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        org.jdesktop.layout.GroupLayout clarinPanelLayout = new org.jdesktop.layout.GroupLayout(clarinPanel);
        clarinPanel.setLayout(clarinPanelLayout);
        clarinPanelLayout.setHorizontalGroup(
            clarinPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 342, Short.MAX_VALUE)
        );
        clarinPanelLayout.setVerticalGroup(
            clarinPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 288, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(clarinPanel);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel3);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jButton1.setVisible(false);
        jProgressBar1.setVisible(true);
        this.doLayout();
        new Thread() {

            public void run() {
                CmdiProfileReader cmdiProfileReader = new CmdiProfileReader();
                cmdiProfileReader.refreshProfiles(jProgressBar1);
                jProgressBar1.setVisible(false);
                jButton1.setVisible(true);
                doLayout();
            }
        }.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            String newDirectoryName = JOptionPane.showInputDialog(LinorgWindowManager.getSingleInstance().linorgFrame, "Enter the name for the new template", LinorgWindowManager.getSingleInstance().linorgFrame.getTitle(), JOptionPane.PLAIN_MESSAGE, null, null, null).toString();
            // if the user cancels the directory string will be a empty string.
            if (ArbilTemplateManager.getSingleInstance().getTemplateFile(newDirectoryName).exists()) {
                LinorgWindowManager.getSingleInstance().addMessageDialogToQueue("The template \"" + newDirectoryName + "\" already exists.", "Templates");
            }
            File freshTemplateFile = ArbilTemplateManager.getSingleInstance().createTemplate(newDirectoryName);
            if (freshTemplateFile != null) {
                GuiHelper.getSingleInstance().openFileInExternalApplication(freshTemplateFile.toURI());
                GuiHelper.getSingleInstance().openFileInExternalApplication(freshTemplateFile.getParentFile().toURI());
            } else {
                LinorgWindowManager.getSingleInstance().addMessageDialogToQueue("The template \"" + newDirectoryName + "\" could not be created.", "Templates");
            }
//                    LinorgWindowManager.getSingleInstance().addMessageDialogToQueue("This action is not yet available.", "Templates");
            //GuiHelper.linorgWindowManager.openUrlWindow(evt.getActionCommand() + templateList.get(evt.getActionCommand()).toString(), new File(templateList.get(evt.getActionCommand()).toString()).toURL());
//                    System.out.println("setting template: " + evt.getActionCommand());
//                    ArbilTemplateManager.getSingleInstance().setCurrentTemplate(evt.getActionCommand());
        } catch (Exception e) {
            GuiHelper.linorgBugCatcher.logError(e);
        }
        populateLists();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void populateLists() {
        templatesPanel.removeAll();
        templatesPanel.setLayout(new javax.swing.BoxLayout(templatesPanel, javax.swing.BoxLayout.PAGE_AXIS));
        // add built in types
        for (String currentTemplateName : ArbilTemplateManager.getSingleInstance().builtInTemplates) {
            JCheckBox templateCheckBox;
            templateCheckBox = new JCheckBox();
            templateCheckBox.setText(currentTemplateName);
            templateCheckBox.setName(currentTemplateName);
            templateCheckBox.setActionCommand(currentTemplateName);
            templateCheckBox.setToolTipText(currentTemplateName);
            templateCheckBox.addActionListener(new java.awt.event.ActionListener() {

                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    try {
//                        if (leadSelectedTreeNode != null) {
//                            leadSelectedTreeNode.requestAddNode(evt.getActionCommand(), ((JMenuItem) evt.getSource()).getText());
//                        } else {
//                            // no nodes found that were valid imdi tree objects so we can assume that tis is the tree root
//                            ImdiTreeObject.requestRootAddNode(evt.getActionCommand(), ((JMenuItem) evt.getSource()).getText());
//                        }
                    } catch (Exception ex) {
                        GuiHelper.linorgBugCatcher.logError(ex);
                    }
                }
            });
            templatesPanel.add(templateCheckBox);
        }
        // add custom templates
        for (String currentTemplateName : ArbilTemplateManager.getSingleInstance().getAvailableTemplates()) {
            JCheckBox templateCheckBox;
            templateCheckBox = new JCheckBox();
            templateCheckBox.setText(currentTemplateName);
            templateCheckBox.setName(currentTemplateName);
            templateCheckBox.setActionCommand(currentTemplateName);
            templateCheckBox.setToolTipText(currentTemplateName);
            templateCheckBox.addActionListener(new java.awt.event.ActionListener() {

                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    try {
//                        if (leadSelectedTreeNode != null) {
//                            leadSelectedTreeNode.requestAddNode(evt.getActionCommand(), ((JMenuItem) evt.getSource()).getText());
//                        } else {
//                            // no nodes found that were valid imdi tree objects so we can assume that tis is the tree root
//                            ImdiTreeObject.requestRootAddNode(evt.getActionCommand(), ((JMenuItem) evt.getSource()).getText());
//                        }
                    } catch (Exception ex) {
                        GuiHelper.linorgBugCatcher.logError(ex);
                    }
                }
            });
            templatesPanel.add(templateCheckBox);
        }
        templatesPanel.doLayout();
        // add clarin types
        clarinPanel.removeAll();
        clarinPanel.setLayout(new javax.swing.BoxLayout(clarinPanel, javax.swing.BoxLayout.PAGE_AXIS));
        CmdiProfileReader cmdiProfileReader = new CmdiProfileReader();
        for (CmdiProfileReader.CmdiProfile currentCmdiProfile : cmdiProfileReader.cmdiProfileArray) {
            JCheckBox clarinProfileCheckBox;
            clarinProfileCheckBox = new JCheckBox();
            clarinProfileCheckBox.setText(currentCmdiProfile.name);
            clarinProfileCheckBox.setName(currentCmdiProfile.name);
            clarinProfileCheckBox.setActionCommand(currentCmdiProfile.getXsdHref());
            clarinProfileCheckBox.setToolTipText(currentCmdiProfile.description);
            clarinProfileCheckBox.addActionListener(new java.awt.event.ActionListener() {

                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    try {
//                        if (leadSelectedTreeNode != null) {
//                            leadSelectedTreeNode.requestAddNode(evt.getActionCommand(), ((JMenuItem) evt.getSource()).getText());
//                        } else {
//                            // no nodes found that were valid imdi tree objects so we can assume that tis is the tree root
//                            ImdiTreeObject.requestRootAddNode(evt.getActionCommand(), ((JMenuItem) evt.getSource()).getText());
//                        }
                    } catch (Exception ex) {
                        GuiHelper.linorgBugCatcher.logError(ex);
                    }
                }
            });
            clarinPanel.add(clarinProfileCheckBox);
        }
        clarinPanel.doLayout();
    }

    public void showTemplatesDialogue() {
        JDialog dialog = new JDialog(LinorgWindowManager.getSingleInstance().linorgFrame, "Available Templates & Profiles", true);
        dialog.setContentPane(new TemplateDialogue());
        dialog.pack();
        dialog.setVisible(true);
//        JFrame testFrame = new JFrame("Available Templates & Profiles");
//        testFrame.getContentPane().add(new TemplateDialogue());
//        testFrame.doLayout();
//        testFrame.pack();
//        testFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
//        testFrame.setVisible(true);
    }

    public static void main(String[] args) {
        JFrame testFrame = new JFrame();
        testFrame.getContentPane().add(new TemplateDialogue());
        testFrame.doLayout();
        testFrame.pack();
        testFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        testFrame.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel clarinPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel templatesPanel;
    // End of variables declaration//GEN-END:variables
}
